Primeira solução do primeiro exercício
rodrigogazevedo/helpperOriginsBootcamp pull request #1
Opened 2021-10-29 22:15 UTC by rodrigogazevedo

Adicionando a primeira solução do primeiro exercício

2021-10-29 22:42 UTC, rodrigogazevedo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Exercício 1](https://trello.com/c/Tqvi8C0i/55-exerc%C3%ADcio-1)

2021-10-30 18:48 UTC, LuizJarduli requested changes

2021-10-30 18:48 UTC, LuizJarduli commented on sprint1/exercicio1a.ts
> +        let letter: string = word.charAt(i);
para variáveis imutáveis, ou seja, o valor dela não será re-atribuído, é interessante usar const no lugar

2021-10-30 18:48 UTC, LuizJarduli commented on sprint1/exercicio1a.ts
> +        return 1;
não seria ideal retornar 0? retornar 1 pode confundir com vogal encontrada

2021-10-30 18:48 UTC, LuizJarduli commented on sprint1/exercicio1a.ts
> +    return countVogel;
Seria interessante retornar um log ou em uma div o resultado, pois somente retornar, não veremos o resultado e o QA não poderá testar por completo seu exercício

2021-10-30 18:48 UTC, LuizJarduli commented on sprint1/exercicio1a.ts
> +    for (let i = 0; i < word.length; i++) {
Seria uma interessante alternativa usar o split  para quebrar a string, em conjunto com o forEach para deixar sua solução mais legível.

split: (https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/String/split)
forEach: (https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach)

2021-10-30 18:48 UTC, LuizJarduli commented on sprint1/exercicio1b.ts
> +    return countVogel;
o ideal seria retornar em uma div ou logar o resultado no terminal, para que o time de QA possa testar

2021-10-30 18:48 UTC, LuizJarduli commented on sprint1/exercicio1b.ts
> +        let letter: any = word.charAt(i);
evite usar o tipo **any**, utilize tipos mais explicitos e diretos, pois essa é o ponto da utilização do typescript, nesse caso o tipo string seria o mais ideal

2021-10-30 18:48 UTC, LuizJarduli commented on sprint1/exercicio1b.ts
> +        return 1;
não seria ideal retornar 0? retornar 1 pode confundir com vogal encontrada

2021-11-01 04:36 UTC, rodrigogazevedo commented on sprint1/exercicio1a.ts
> +        let letter: string = word.charAt(i);
Retirei a variável para a aplicação do uso do foreach. Não havia mais necessidade de criar a variável.

2021-11-01 04:37 UTC, rodrigogazevedo commented on sprint1/exercicio1a.ts
> +        return 1;
acho melhor retornar -1, porque retornar 0 poderia entender que a função estaria tudo ok

2021-11-01 04:37 UTC, rodrigogazevedo commented on sprint1/exercicio1a.ts
> +    return countVogel;
coloquei para imprimir o log no console

2021-11-01 04:37 UTC, rodrigogazevedo commented on sprint1/exercicio1a.ts
> +    for (let i = 0; i < word.length; i++) {
alterado para o foreach

2021-11-01 04:38 UTC, rodrigogazevedo commented on sprint1/exercicio1b.ts
> +    return countVogel;
colocado uma div com o valor encontrado

2021-11-01 04:38 UTC, rodrigogazevedo commented on sprint1/exercicio1b.ts
> +        let letter: any = word.charAt(i);
retirado devido a criação do foreach

2021-11-01 04:38 UTC, rodrigogazevedo commented on sprint1/exercicio1b.ts
> +        return 1;
acho melhor retornar -1, porque retornar 0 poderia entender que a função estaria tudo ok

2021-11-02 17:28 UTC, LuizJarduli requested changes

2021-11-02 17:28 UTC, LuizJarduli commented on sprint1/exercicio1b.ts
> +    var word: string = (<HTMLInputElement>document.getElementById("input_word")).value;
para variáveis imutáveis, utilize **const** ao invés de **var** ou **let**, isso vale para todo seu código

2021-11-02 17:28 UTC, LuizJarduli commented on sprint1/exercicio1b.ts
> +    var word: string = (<HTMLInputElement>document.getElementById("input_word")).value;
Também é importante tipar o retorno de funções, até aquelas com retorno void

2021-11-02 17:28 UTC, LuizJarduli commented on sprint1/exercicio1a.ts
> +    if (typeof word !== 'string') {
Também é importante tipar o retorno de funções, até aquelas com retorno void

2021-11-03 00:01 UTC, closed without merging