Solução do segundo exercício
rodrigogazevedo/helpperOriginsBootcamp pull request #3
Opened 2021-11-09 03:43 UTC by rodrigogazevedo

2021-11-09 04:23 UTC, rodrigogazevedo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Exercício 2](https://trello.com/c/mu0jSriC/159-exerc%C3%ADcio-2)

2021-11-10 23:38 UTC, LuizJarduli requested changes

2021-11-10 23:38 UTC, LuizJarduli commented on sprint1/exercicio2/exercicio2a.ts
> +    for(var index in list) {
utilize `let` ao invés de `var` para resolução dos exercícios, é preferível para escopos mais restritos em seu código

2021-11-10 23:38 UTC, LuizJarduli commented on sprint1/exercicio2/exercicio2a.ts
> +let list : {id: number, name: string, bio: string}[] = [
Utilize `const` para variáveis que não possuem seu valor mutável ao longo do código, ou seja, não tem seu valor re-atribuido.

Uma dica, crie uma `interface` para tipar sua lista, fica mais legível do que deixar implícito esse objeto.
Mais sobre interfaces em TypeScript aqui: https://www.typescriptlang.org/docs/handbook/interfaces.html

2021-11-10 23:38 UTC, LuizJarduli commented on sprint1/exercicio2/exercicio2a.ts
> +    const f = foundBio.map(function(key) {
Importante tipar as `consts`

Outro ponto, `f` não é um nome muito legível para uma variável, sempre importante ter esse cuidado ao declarar

2021-11-10 23:38 UTC, LuizJarduli commented on sprint1/exercicio2/exercicio2b.ts
> +    for(var index in list2) {
utilize `let` ao invés de `var` para resolução dos exercícios, é preferível para escopos mais restritos em seu código

2021-11-10 23:38 UTC, LuizJarduli commented on sprint1/exercicio2/exercicio2b.ts
> +    const f = foundBio.map(function(key) {
Importante tipar as `consts`

Outro ponto, `f` não é um nome muito legível para uma variável, sempre importante ter esse cuidado ao declarar

2021-11-10 23:38 UTC, LuizJarduli commented on sprint1/exercicio2/exercicio2b.ts
> +let list2 : {id: number, name: string, bio: string}[] = [
Utilize `const` para variáveis que não possuem seu valor mutável ao longo do código, ou seja, não tem seu valor re-atribuido.

Uma dica, crie uma `interface` para tipar sua lista, fica mais legível do que deixar implícito esse objeto.
Mais sobre interfaces em TypeScript aqui: https://www.typescriptlang.org/docs/handbook/interfaces.html

2021-11-10 23:38 UTC, LuizJarduli commented on sprint1/exercicio2/exercicio2c.ts
> +    {"id" : 1, "name": "Ada Lovelace", "bio" : "Ada Lovelace, foi uma matemática e escritora inglesa reconhecida por ter escrito o primeiro algoritmo para ser processado por uma máquina"},
Utilize `const` para variáveis que não possuem seu valor mutável ao longo do código, ou seja, não tem seu valor re-atribuido.

Uma dica, crie uma `interface` para tipar sua lista, fica mais legível do que deixar implícito esse objeto.
Mais sobre interfaces em TypeScript aqui: https://www.typescriptlang.org/docs/handbook/interfaces.html

2021-11-10 23:38 UTC, LuizJarduli commented on sprint1/exercicio2/exercicio2c.ts
> +    for(var index in list3) {
utilize `let` ao invés de `var` para resolução dos exercícios, é preferível para escopos mais restritos em seu código. Outra dica, poderia utilizar `const` para declarar sua `newList` já que não tem seu valor re-atribuido ao longo do exercício

2021-11-10 23:38 UTC, LuizJarduli commented on sprint1/exercicio2/exercicio2d.ts
> +let teclado = require('prompt-sync')();
Quando vou executar seu script, está dando um erro nesse módulo, falta configurar o `package.json` e suas dependências.
![image](https://user-images.githubusercontent.com/50338486/141210478-f494c4ac-b27e-487f-b9c5-fe7cba3af2fb.png)

2021-11-16 00:27 UTC, rodrigogazevedo commented on sprint1/exercicio2/exercicio2d.ts
> +let teclado = require('prompt-sync')();
Verdade, esqueci de instalar.
Corrigido

2021-11-16 00:27 UTC, rodrigogazevedo commented on sprint1/exercicio2/exercicio2c.ts
> +    for(var index in list3) {
ok

2021-11-16 00:28 UTC, rodrigogazevedo commented on sprint1/exercicio2/exercicio2c.ts
> +    {"id" : 1, "name": "Ada Lovelace", "bio" : "Ada Lovelace, foi uma matemática e escritora inglesa reconhecida por ter escrito o primeiro algoritmo para ser processado por uma máquina"},
ok

2021-11-16 00:28 UTC, rodrigogazevedo commented on sprint1/exercicio2/exercicio2b.ts
> +let list2 : {id: number, name: string, bio: string}[] = [
ok

2021-11-16 00:28 UTC, rodrigogazevedo commented on sprint1/exercicio2/exercicio2b.ts
> +    const f = foundBio.map(function(key) {
ok.
Foi erro meu de deixar a variável assim (_f_).
Corrigido.

2021-11-16 00:28 UTC, rodrigogazevedo commented on sprint1/exercicio2/exercicio2b.ts
> +    for(var index in list2) {
ok

2021-11-16 00:29 UTC, rodrigogazevedo commented on sprint1/exercicio2/exercicio2a.ts
> +    const f = foundBio.map(function(key) {
ok.
Foi erro meu de deixar a variável assim (f).
Corrigido.

2021-11-16 00:29 UTC, rodrigogazevedo commented on sprint1/exercicio2/exercicio2a.ts
> +let list : {id: number, name: string, bio: string}[] = [
ok

2021-11-16 00:29 UTC, rodrigogazevedo commented on sprint1/exercicio2/exercicio2a.ts
> +    for(var index in list) {
ok

2021-11-16 00:30 UTC, rodrigogazevedo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Exercício 2](https://trello.com/c/mu0jSriC/159-exerc%C3%ADcio-2)

2021-11-23 01:25 UTC, merged