Solução do terceiro exercício
rodrigogazevedo/helpperOriginsBootcamp pull request #4
Opened 2021-11-09 04:22 UTC by rodrigogazevedo

2021-11-09 04:24 UTC, rodrigogazevedo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Exercício 3](https://trello.com/c/LpHKdTsL/160-exerc%C3%ADcio-3)

2021-11-10 23:59 UTC, LuizJarduli requested changes

2021-11-10 23:59 UTC, LuizJarduli commented on sprint1/exercicio3/exercicio3funcional.ts
> +    result2.push({property: "média", value: verifyAverageNumbersFuncional(list)});
O ideal é que uma função no paradigma funcional não deve acessar variáveis globais (`result2`) para seu processamento interno, e sim utilize os parâmetros de entrada e gere novos dados de retorno.

2021-11-10 23:59 UTC, LuizJarduli commented on sprint1/exercicio3/exercicio3funcional.ts
> +    const quantity = list.length;
Importante tipar as `consts`

2021-11-10 23:59 UTC, LuizJarduli commented on sprint1/exercicio3/exercicio3imperativo.ts
> +    list.forEach(function (value) {
A ideia do paradigma imperativo é não utilizar as funções do js para resolução, ao invés de `forEach`, para atender o exercício dentro do paradigma o ideal seria utilizar um laço de repetição para iterar a lista.

Isso vale para todo o resto do exercício imperativo

2021-11-16 00:16 UTC, rodrigogazevedo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Exercício 3](https://trello.com/c/LpHKdTsL/160-exerc%C3%ADcio-3)

2021-11-16 00:17 UTC, rodrigogazevedo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Exercício 3](https://trello.com/c/LpHKdTsL/160-exerc%C3%ADcio-3)

2021-11-16 00:33 UTC, rodrigogazevedo commented on sprint1/exercicio3/exercicio3funcional.ts
> +    result2.push({property: "média", value: verifyAverageNumbersFuncional(list)});
Acho que entendi o que você quis dizer, mas nesse caso a lista (_result2_) seria somente para armazenar os valores novos, não teria interação direta com as funções.

Trouxe ele para dentro da função principal e criei ela (_result2_) como uma variável local.

2021-11-16 00:34 UTC, rodrigogazevedo commented on sprint1/exercicio3/exercicio3funcional.ts
> +    const quantity = list.length;
ok

2021-11-16 00:34 UTC, rodrigogazevedo commented on sprint1/exercicio3/exercicio3imperativo.ts
> +    list.forEach(function (value) {
ok

2021-11-23 01:25 UTC, merged